(()=>{const initial=window.__INITIAL_ENTRIES__||[];let entries=[...initial],activeCategory='all',currentEntry=null;const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];const labels={all:'収録情報',weapons:'武器種図鑑',cards:'武器カード・薬図鑑',jobs:'ジョブ図鑑',emblems:'紋章図鑑',enemies:'敵図鑑＆攻略情報',other:'戦闘・報酬'};const accents={lime:'#caff00',amber:'#ffc247',rose:'#ff5f7a',violet:'#9a7cff',ice:'#8ee6ff',sky:'#50bfff',red:'#ff4c39',teal:'#47d7bd'};
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showArchive(){ $('#modeSelect').classList.add('hidden');$('#archive').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});render() }
function showHome(){ $('#archive').classList.add('hidden');$('#modeSelect').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'}) }
function filtered(){const q=$('#search').value.trim().toLowerCase();let list=entries.filter(e=>(activeCategory==='all'||e.category===activeCategory)&&(!q||[e.title,e.subtitle,e.summary,e.body,...(e.tags||[])].join(' ').toLowerCase().includes(q)));const sort=$('#sort').value;return list.sort(sort==='title'?(a,b)=>a.title.localeCompare(b.title,'ja'):sort==='updated'?(a,b)=>(b.updatedAt||0)-(a.updatedAt||0):(a,b)=>(a.sortOrder||0)-(b.sortOrder||0))}
function render(){const list=filtered();$('#countAll').textContent=entries.length;$('#resultTitle').textContent=labels[activeCategory];$('#resultCount').textContent=list.length+'件';$('#empty').classList.toggle('hidden',list.length>0);$('#entryGrid').innerHTML=list.map(e=>`<button class="entry ${e.category==='enemies'?'enemy-entry':''} accent-${esc(e.accent)}" data-id="${esc(e.id)}" style="--accent:${accents[e.accent]||accents.lime}"><span class="entry-kind">${esc(labels[e.category]||e.category)}</span><h2>${esc(e.title)}</h2><span class="subtitle">${esc(e.subtitle)}</span><p class="summary">${esc(e.summary)}</p><footer><span class="tags">${(e.tags||[]).slice(0,3).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</span><span class="entry-arrow">↗</span></footer></button>`).join('')}
function openDetail(id){currentEntry=entries.find(e=>e.id===id);if(!currentEntry)return;$('#detailAccent').style.background=accents[currentEntry.accent]||accents.lime;$('#detailKind').textContent=labels[currentEntry.category];$('#detailTitle').textContent=currentEntry.title;$('#detailSubtitle').textContent=currentEntry.subtitle||'';$('#detailSummary').textContent=currentEntry.summary||'';$('#detailBody').textContent=currentEntry.body||'';$('#detailSource').textContent=(currentEntry.source||'クラウド編集')+'｜改訂 '+(currentEntry.revision||0);$('#detailTags').innerHTML=(currentEntry.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('');$('#detailDialog').showModal()}
function openEditor(entry){const f=$('#editorForm');f.reset();$('#formMessage').textContent='';if(entry){$('#editorHeading').textContent='記録を編集';for(const k of ['id','revision','category','accent','title','subtitle','summary','body'])if(f.elements[k])f.elements[k].value=entry[k]??'';f.elements.tags.value=(entry.tags||[]).join(', ')}else{$('#editorHeading').textContent='記録を追加';f.elements.id.value='';f.elements.revision.value='0'}$('#editorDialog').showModal()}
async function load(){try{const r=await fetch('/api/entries',{headers:{accept:'application/json'}});if(!r.ok)throw new Error();const data=await r.json();entries=data.entries||initial;$('#syncState').classList.add('ready');$('#syncState').innerHTML='<i></i>クラウド同期';render()}catch{$('#syncState').classList.add('error');$('#syncState').innerHTML='<i></i>初期データ表示中';render()}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const a=b.dataset.action;if(b.dataset.game==='ten-saviors')showArchive();else if(b.dataset.id)openDetail(b.dataset.id);else if(b.dataset.category){activeCategory=b.dataset.category;$$('.category').forEach(x=>x.classList.toggle('active',x===b));render()}else if(a==='home')showHome();else if(a==='open-editor')openEditor();else if(a==='close-detail')$('#detailDialog').close();else if(a==='close-editor')$('#editorDialog').close();else if(a==='edit-current'){ $('#detailDialog').close();openEditor(currentEntry)}else if(a==='paste-ccfolia'){navigator.clipboard.readText().then(t=>{const area=$('#editorForm').elements.body;area.value+=(area.value?'\n':'')+t;$('#formMessage').textContent='クリップボードの文章を追加しました。'}).catch(()=>{$('#formMessage').textContent='ブラウザの貼り付け許可が必要です。詳細欄へ直接貼り付けることもできます。'})}});
$('#search').addEventListener('input',render);$('#sort').addEventListener('change',render);$('#detailDialog').addEventListener('click',e=>{if(e.target===$('#detailDialog'))$('#detailDialog').close()});$('#editorDialog').addEventListener('click',e=>{if(e.target===$('#editorDialog'))$('#editorDialog').close()});
$('#editorForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f),body={id:fd.get('id')||undefined,revision:Number(fd.get('revision')||0),game:'ten-saviors',category:fd.get('category'),accent:fd.get('accent'),title:fd.get('title'),subtitle:fd.get('subtitle'),summary:fd.get('summary'),body:fd.get('body'),tags:String(fd.get('tags')||'').split(/[,、]/).map(x=>x.trim()).filter(Boolean)};$('#formMessage').textContent='保存しています…';try{const r=await fetch('/api/entries',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(r.status===409){$('#formMessage').textContent='別の端末で更新されています。最新情報を読み込みました。';await load();return}if(!r.ok)throw new Error(data.error||'保存できませんでした');entries=entries.filter(x=>x.id!==data.entry.id).concat(data.entry);render();$('#syncState').classList.add('ready');$('#formMessage').textContent='保存しました。';setTimeout(()=>$('#editorDialog').close(),450)}catch(err){$('#formMessage').textContent=err.message||'保存できませんでした。'}});load();})();
